Automattic/republication-tracker-tool

assets/widget.js, includes/class-settings.php, includes/pixel.php, includes/shareable-content.php, republication-tracker-tool.php
- Changes the way we fire the pixel. Instead of firing it at `/wp-content/plugins/republication-tracker-tool/?query_params`, we'll now fire it at `site.com/*?query_params`. This _should be_ backwards compatible so sites experiencing the 403 issue in their republished posts should have the issue resolved once updated.
- Updates the `modal_actions` function to use `.html()` instead of `.text()` when copying the content into the sharable modal so that the pixel `&`'s don't get encoded into `&amp;` and cause issues if pasted into a CMS that doesn't automatically decode html entities.
For #50 and #48.
- The pixel redirect when the pixel url is requested.
Steps to …
=> Fix 403 forbidden pixel issue

includes/pixel.php, includes/shareable-content.php
- Adds a `max-width:200px;` style attribute to the image pixel as a fallback. However, this doesn't work with Gutenberg since the image is made into an image block when it is pasted and the style attribute is stripped. Sites may need to add custom css when pasting it in.
For #55
- Pixel image element
=> Adds a max-width style attribute to the image pixel

docs/README.md, docs/removing-elements-from-shareable-content.md, includes/shareable-content.php
- Removes the unsetting of specific elements from the `allowed_tags_excerpt` array so elements like images, videos, etc. aren't removed from the shareable content box.
For #49
- Shareable content
Steps to test this PR:
1. Open Shareable Content box for posts with images, videos, and buttons.
=> Only remove `form` elements from shareable content

docs/README.md, docs/removing-republish-button-from-categories.md, includes/class-article-settings.php, includes/class-widget.php
- Adds a custom metabox to the post editor document sidebar to check/uncheck if the post should hide the Republication sharing widget
- Adds a new filter, `hide_republication_widget`, which allows developers to programmatically hide the sharing button on any specific post/page/taxonomy
- It is currently set up to allow the filter to take priority. For example, if category A is hidden through the filter, but post 3 inside of category A wants to show the button, toggling the checkbox in the post editor won't make the button show.
For #51
- Republication sharing button on posts
Steps to test this PR:
1. Make sure the on/off checkbox in the post editor works
2. Make …
=> Toggle republication on/off for posts

assets/widget.js, includes/class-widget.php
- Swaps `$btn` to look for clicks on `.republication-tracker-tool-button` instead of `#cc-btn`
- Changes `WRTT_PATH` constant the `$republication_plugin_path` variable so that we don't get "const. cannot be redefined" errors
- Sets `$has_instance` global class variable that will update to `true` if an instance of the widget already exists, and uses this to make sure the modal is only output once on the page
For #66 
- Republication frontend widget button and modal
Steps to test this PR:
1. Add multiple instances of the Republication widget via widget areas
2. Add the widget to the post template using this method: …
=> Allow multiple instances of Republication widget to coexist

assets/widget.js
- This allows the modal to show if the url contains `#show-republish`.
- It also adds a close handler if the user presses the Escape key.
- To do both these things, there's a `show_modal( $modal )` function and a `close_modal( $modal )` function
If approved, this would address #76. The Escape button part is because many keyboard users expect the escape key to close things like modals. This can be an [accessibility best practice](https://simplyaccessible.com/article/closing-modals/).
- opening and closing of the modal and display of the modal's content
Steps to test this PR:
1. Open a modal with the click on the widget button
2. Open a modal with the URL hash
3. Close the modal with a click on the close button
4. …
=> modal show by URL hash

assets/widget.css, includes/class-widget.php, includes/shareable-content.php, package-lock.json, package.json
Adds support for AMP pages. 
Closes #57 
1. Add the republication tracker widget as described [in the docs](https://github.com/Automattic/republication-tracker-tool/tree/master/docs)
2. Visit a post in non-AMP mode - observe everything working as before 
3. Visit a post in AMP mode - ~observe the in the widget area is the same, but after clicking the button which opens the modal, a new browser tab opens with the modal content~ observe that the modal is also shown after clicking the button, as on the non-AMP version
4. Observe that the AMP version does not sport a "Copy to clipboard" button and instead links to the original article
=> Add AMP support

includes/shareable-content.php, republication-tracker-tool.php
Fixes a bug.
1. On `master`, disable "Display attribution" in RTT settings (in Settings->Reading)
2. Observe that the tracking pixel is missing in the copyable content
3. Switch to this branch, observe the pixel is in copyable content regardless of the "Display attribution" setting
=> Add tracking pixel if attribution statement is not displayed

includes/class-widget.php, includes/shareable-content.php
Links to external sites should have this attribute. More on that here: https://web.dev/external-anchors-use-rel-noopener
1. On `master`, run Lighthouse (in Chrome devtools) "Best Practices" audit
2. Observe issue about unsafe links reported
3. Switch to this branch, rerun the audit, observe no issue (at least not originating from this plugin's code)
=> Fix: rel attribute on links

includes/pixel.php
As it says on the tin.
1. On `master`,
2. Place the RTT widget in the sidebar, and use it to copy content of a post
3. To verify that a ping is sent to GA, log something [around here](https://github.com/Automattic/republication-tracker-tool/blob/8f991db9f567a4f49bd4fe5c50d40b6d5583d739/includes/pixel.php#L108)
4. Insert the copied content into the post editor, while in code editor mode
5. Observe that a ping is sent to GA, because the editor contains the tracking pixel
6. Switch to this branch. observe the ping is not sent
7. Publish the republished post, visit it - observe the ping is sent to GA as expected
=> fix: prevent GA pings from WP Admin

includes/pixel.php
Fixes a small thing. Technically, `exit` should be performed instead of `return` to finish the ping request . 
Same as in #119
=> fix: exit if pinging from wp-admin

includes/class-widget.php, includes/shareable-content.php
This PR adds the HTML attributes `role="dialog"` and `aria-modal="true"` to the modal dialog opened by the plugin, to improve accessibility. This change was based on some feedback in a publisher's third-part accessibility report.
Closes #135
1. Apply the PR.
2. Click the Republish this Story button on your test site.
3. Inspect the HTML; confirm that the `role="dialog"` and `aria-modal="true"` and present in the markup on the dialog box container:
=> Add `role` and `aria-modal` attributes to popup

assets/widget.css, includes/shareable-content.php
This PR adds the a label to the modal dialog close button that can be read by screen readers, but is not actually visible.
It also adds the `aria-hidden="true"` to the `X` that's used as the visible close button label, so screen readers will ignore it. 
Closes #134
1. Apply the PR. 
2. Open the dialog on a test site; confirm that the button displays an X, and no visible label. 
3. Confirm that the screen reader label is available in the source:
4. Bonus test: use a screen reader (like Mac's VoiceOver Utility, under System Preferences > Accessibility > VoiceOver), to navigate the page and confirm that it reads the 'Close window' text:
=> Add screen reader accessible label to the modal close button

assets/widget.css
This PR increases the contrast of the Republication button by switching it to a darker blue -- this improves accessibility by meeting WCAG 2.0 level AAA contrast ratio of 4.5:1 for larger text.
I tried to go with a colour that wouldn't read as extremely different from the current blue, and tweaked the border and text shadow colours to match. That being said, this issue originally came from a third-party accessibility review one of our publishers got, and is also fixed on their site using Custom CSS. So if this seems like too much of a change a this point, it would also work to close this issue as a `wontfix` and address this on a per-site basis if it comes up again in the future. 
Closes #133
1. Start with a site running the Republication Tracker plugin; view the button on the front end: …
=> fix: increase button background contrast

.circleci/config.yml
New release, because latest failed on WPORG release due to outdated CI configuration.
=> Release May 24th

includes/class-article-settings.php
Updates code that determines whether Republication Tracker Tool's checkbox is shown in the post editor.
The checkbox is currently visible only on alternating views of the post editor, with its settings getting lost in between. Closes #67 & #170.
1. Create a post and check the "Hide the Republication sharing widget on this post?" box in the post settings.
2. Publish the post.
3. View the post on the frontend. Observe that the republication widget is not present.
4. Click "Edit Post".
5. Observe that the checkbox has been replaced with the notice "The Republication sharing widget on this post is programatically disabled through the hide_republication_widget filter. Read more about this filter." (This is a known issue: https://github.com/Automattic/republication-tracker-tool/issues/67)
6. …
=> Consistent visibility of "Hide Republish Button" checkbox

README.md, includes/class-settings.php, includes/pixel.php, republication-tracker-tool.php
Adds GA4 support for the tracking pixel. Also updates the README and bumps the "Tested up to" tag to WP 6.2 for the WP.org plugin repository.
Closes `https://app.asana.com/0/1200550061930446/1204364074266317`.
1. Check out this branch. Go to WP admin > Settings > Reading and find the Republication Tracker Tool section.
2. Confirm that instead of a single "Google Analytics ID" field, there are now three fields:
- **Google Analytics UA ID:** This is the former "Google Analytics ID", now labeled more specifically and with help text describing its imminent deprecation. If your plugin had this field filled out before, the value should remain.
- **Google Analytics 4 ID:** This is the GA4 measurement ID. Fill this out with a GA4 measurement ID. Fill this in and follow the help text link if you …
=> feat: add support to tracking pixel for GA4

includes/class-article-settings.php
Restores visibility of the "shares" table of details in the edit post metabox. The `fixed` classname causes it to be hidden from view, possibly from a recent WP admin style change.
Closes `1204323000227080/1204364074266311`.
1. On `master` or `release`, share an article to another site via the Republication Tracker Tool widget. 
2. Edit the post on the original site and observe that the metabox shows total shares, but not the table of detailed share info:
3. Check out this branch, refresh the editor, and confirm that the table is back:
=> fix: restore visibility of "shares" table in metabox

includes/pixel.php, republication-tracker-tool.php
#183 introduced support for GA4 tracking pixels in addition to GA3. In that PR we changed the URL param for GA3 ID from `ga` to `ga3`, for clarity. However, this will break functionality for content that has already been shared prior to this change. This PR restores support for the plain `ga` param and treats it the same as the new `ga3` param, to avoid feature regression for this legacy content.
1. On `master`, copy the HTML for a post but replace all instances of `ga3` with `ga`.
2. Share this modified HTML to another site.
3. View the shared content's front-end.
4. In your GA3 dashboard > Realtime, observe that pageviews of the shared content are not tracked.
5. Check out this branch and re-view the shared content.
6. This time confirm that it is tracked.
=> fix: support old "ga" param for GA3 tracking

includes/pixel.php, republication-tracker-tool.php
GA4 events require a `client_id` param. This plugin attempts to extract it from the `_ga` cookie if set, but occasionally this cookie can't be fetched or hasn't been set yet (possibly due to server-level caching). This PR creates a fallback that first looks for the `newspack-cid` cookie (which is the fallback client ID set for Newspack Campaigns and Reader Activation features) and if that can't be fetched either, generates a random 9-digit string and attempts to store that as a `newspack-cid` cookie so the ID can be fetched in future requests in the same session.
Kind of hard to know how to replicate the scenario where `$_COOKIES` will be empty, but open your GA dashboard's Real Time events report and ensure that viewing shared content always results in a `page_view` event with the …
=> fix: create fallback client id for GA if none exists

assets/widget.css, assets/widget.js, includes/class-widget.php, includes/shareable-content.php
This PR adds a number of accessibility improvements to the republication tracker modal:
* It adds an `aria-labelledby` attribute to the modal, and uses the existing modal header as a reference.
* It changes the close button to an actual button (and adds some general override styles so it should appear the same as it does now). 
* When the modal is opened, it moves the keyboard focus to the 'Close' button.
* When you tab through the modal, it traps focus inside of the modal (so when you get to the copy key and tab further, it kicks you back to the close button, instead of letting you tab outside and behind of the modal). 
* When you copy the content using the keyboard (focus on the button and hit enter), the button retains focus.
See 200133283613421-as-1206162676524753
1. Apply the PR.
2. …
=> Accessibility improvements to republication modal

includes/class-widget.php, republication-tracker-tool.php
This plugin was appending a static version number to enqueued JavaScript and CSS; this number wasn't getting updated with each release, though, so the files would be cached after updates.
I replaced the version number with `filemtime` instead.
1. Apply the PR. 
2. View the source and confirm a `ver` query string and value is being added to the paths enqueuing the plugin's CSS and JS files, like `?ver=1704225350`.
=> fix: update enqueued files to use filemtime to enable proper caching
